- name: Amazon AWS
  image: logo_aws.svg
  width: 140
  height: 54
  code: "aws_instances:  &#10;
         &nbsp;aws_instances:&#10;
         &nbsp;&nbsp;instance_type: 'micro'&#10;
         &nbsp;&nbsp;ami: ''&#10;
         &nbsp;&nbsp;user_data:&#10;
         &nbsp;&nbsp;&nbsp;apt-get install ruby mysql&#10;
         &nbsp;&nbsp;&nbsp;git clone git@github.com/koding/project.git&#10;
         &nbsp;&nbsp;&nbsp;chef-solo -c solo.rb -j web.json"
- name: Digital Ocean
  image: logo_digitalocean.svg
  width: 100
  height: 75
  code: "digitalocean_droplet: &#10;
         &nbsp;dev:&#10;
         &nbsp;&nbsp;image: 'ubuntu-14-04-x64'&#10;
         &nbsp;&nbsp;name: 'my_digital_ocean_dev_vm'&#10;
         &nbsp;&nbsp;region: 'nyc2'&#10;
         &nbsp;&nbsp;size: '512mb'&#10;"
- name: Openstack
  image: logo_openstack.svg
  width: 155
  height: 29
  code: "openstack_compute_instance_v2:	&#10;
         &nbsp;dev:&#10;
         &nbsp;&nbsp;name: my_dev_machine&#10;
         &nbsp;&nbsp;image_id: my_image_uuid&#10;
         &nbsp;&nbsp;key_pair: my_key_pair_name&#10;"
- name: Vagrant
  image: logo_vagrant.svg
  width: 180
  height: 46
  code: "vagrant_instance: &#10;
         &nbsp;vagrant_instance:&#10;
         &nbsp;&nbsp;cpus: 2&#10;
         &nbsp;&nbsp;memory: 2048&#10;
         &nbsp;&nbsp;box: ubuntu/trusty64&#10;"
- name: Microsoft Azure
  image: logo_azure.svg
  width: 190
  height: 27
  active: true
  code: "azure_instances:	&#10;
        &nbsp;name:&#10;
        &nbsp;size: Basic_A1&#10;
        &nbsp;image: 'Ubuntu Server 14.04 LTS'&#10;
        &nbsp;user_data:&#10;
        &nbsp;&nbsp;apt-get install ruby mysql&#10;
        &nbsp;&nbsp;git clone git@github.com/koding/project.git&#10;
        &nbsp;&nbsp;chef-solo -c solo.rb -j web.json"
- name: Google Cloud Platform
  image: logo_gcp.svg
  width: 300
  height: 33
  code: "google_compute_instance&#10;
         &nbsp;google-instance:&#10;
         &nbsp;&nbsp;name:&#10;
         &nbsp;&nbsp;machine_type: f1-micro&#10;
         &nbsp;&nbsp;disk:&#10;
         &nbsp;&nbsp;&nbsp;image: ubuntu-1404-lts&#10;
         &nbsp;&nbsp;zone: us-central1-a&#10;"
- name: Docker
  image: logo_docker.svg
  width: 180
  height: 43
  code: "docker_container:&#10;
        &nbsp;user_data:&#10;
        &nbsp;&nbsp;sudo apt-get update&#10;
        &nbsp;&nbsp;sudo apt-get purge -y lxc-docker&#10;
        &nbsp;&nbsp;sudo apt-get install linux-image-extra-$(uname -r)&#10;
        &nbsp;&nbsp;sudo apt-get install --force-yes docker-engine&#10;
        &nbsp;&nbsp;...&#10"
- name: Softlayer
  image: logo_softlayer.svg
  width: 180
  height: 15
  code: "softlayer_virtual_guest:&#10;
         &nbsp;softlayer-instance:&#10;
         &nbsp;&nbsp;name: softlayer-instance&#10;
         &nbsp;&nbsp;domain: <your-domain>&#10;
         &nbsp;&nbsp;region: dal09&#10;
         &nbsp;&nbsp;image: UBUNTU_14_649&#10;
         &nbsp;&nbsp;cpu: 1&#10;
         &nbsp;&nbsp;ram: 1024&#10;"
- name: Mesosphere
  image: logo_mesos.svg
  width: 240
  height: 43
  code: "mesosphere:&#10;
        &nbsp;user_data:&#10;
        &nbsp;&nbsp;sudo apt-get install -y mesosphere&#10;
        &nbsp;&nbsp;mkdir -p /var/zookeeper&#10;
        &nbsp;&nbsp;chown -R zookeeper /var/zookeeper&#10;
        &nbsp;&nbsp;...&#10;"